import { Match, CallupPlayer } from './types';

export const COUNTRY_CODES: Record<string, string> = {
  'México': 'mx',
  'África do Sul': 'za',
  'Coreia do Sul': 'kr',
  'República Tcheca': 'cz',
  'Canadá': 'ca',
  'Bósnia': 'ba',
  'Estados Unidos': 'us',
  'Paraguai': 'py',
  'Austrália': 'au',
  'Turquia': 'tr',
  'Qatar': 'qa',
  'Suíça': 'ch',
  'Brasil': 'br',
  'Marrocos': 'ma',
  'Haiti': 'ht',
  'Escócia': 'gb-sct',
  'Alemanha': 'de',
  'Curaçao': 'cw',
  'Costa do Marfim': 'ci',
  'Equador': 'ec',
  'Holanda': 'nl',
  'Japão': 'jp',
  'Suécia': 'se',
  'Tunísia': 'tn',
  'Espanha': 'es',
  'Cabo Verde': 'cv',
  'Arábia Saudita': 'sa',
  'Uruguai': 'uy',
  'Bélgica': 'be',
  'Egito': 'eg',
  'Irã': 'ir',
  'Nova Zelândia': 'nz',
  'França': 'fr',
  'Senegal': 'sn',
  'Iraque': 'iq',
  'Noruega': 'no',
  'Argentina': 'ar',
  'Argélia': 'dz',
  'Áustria': 'at',
  'Jordânia': 'jo',
  'Portugal': 'pt',
  'Congo': 'cd',
  'RD Congo': 'cd',
  'Uzbequistão': 'uz',
  'Colômbia': 'co',
  'Inglaterra': 'gb-eng',
  'Croácia': 'hr',
  'Gana': 'gh',
  'Panamá': 'pa',
  'Itália': 'it',
  'Chile': 'cl',
  'Nigéria': 'ng',
  'Camarões': 'cm',
  'Costa Rica': 'cr',
  'Peru': 'pe',
  'Polônia': 'pl',
  'Sérvia': 'rs',
  'Dinamarca': 'dk'
};

export const BRAZIL_PLAYERS: CallupPlayer[] = [
  // Goleiros
  { name: 'Alisson Becker', position: 'Goleiro', club: 'Liverpool' },
  { name: 'Ederson', position: 'Goleiro', club: 'Fenerbahçe' },
  { name: 'Bento', position: 'Goleiro', club: 'Al-Nassr' },
  { name: 'Hugo Souza', position: 'Goleiro', club: 'Corinthians' },
  // Defensores
  { name: 'Danilo', position: 'Defensor', club: 'Botafogo/Juventus/Flamengo' },
  { name: 'Marquinhos', position: 'Defensor', club: 'PSG' },
  { name: 'Gabriel Magalhães', position: 'Defensor', club: 'Arsenal' },
  { name: 'Léo Pereira', position: 'Defensor', club: 'Flamengo' },
  { name: 'Vitor Reis', position: 'Defensor', club: 'Palmeiras' },
  { name: 'Ibañez', position: 'Defensor', club: 'Al-Ahli' },
  { name: 'Gleison Bremer', position: 'Defensor', club: 'Juventus' },
  { name: 'Alex Sandro', position: 'Defensor', club: 'Flamengo' },
  { name: 'Kaiki Bruno', position: 'Defensor', club: 'Cruzeiro' },
  { name: 'Wesley França', position: 'Defensor', club: 'Roma' },
  { name: 'Douglas Santos', position: 'Defensor', club: 'Zenit' },
  { name: 'Éder Militão', position: 'Defensor', club: 'Real Madrid' },
  { name: 'Fabrício Bruno', position: 'Defensor', club: 'Cruzeiro' },
  { name: 'Caio Henrique', position: 'Defensor', club: 'Monaco' },
  { name: 'Luciano Juba', position: 'Defensor', club: 'Bahia' },
  { name: 'Paulo Henrique', position: 'Defensor', club: 'Vasco' },
  { name: 'Wesley', position: 'Defensor', club: 'Roma' },
  { name: 'Vanderson', position: 'Defensor', club: 'Monaco' },
  { name: 'Murillo', position: 'Defensor', club: 'Nottingham Forest' },
  { name: 'Guilherme Arana', position: 'Defensor', club: 'Atlético-MG' },
  { name: 'Wendell', position: 'Defensor', club: 'Porto' },
  // Meio-campistas
  { name: 'Casemiro', position: 'Meio-campista', club: 'Manchester United' },
  { name: 'Bruno Guimarães', position: 'Meio-campista', club: 'Newcastle' },
  { name: 'Lucas Paquetá', position: 'Meio-campista', club: 'West Ham' },
  { name: 'Gabriel Sara', position: 'Meio-campista', club: 'Galatasaray' },
  { name: 'João Gomes', position: 'Meio-campista', club: 'Wolverhampton' },
  { name: 'Andrey Santos', position: 'Meio-campista', club: 'Chelsea' },
  { name: 'Fabinho', position: 'Meio-campista', club: 'Al-Ittihad' },
  { name: 'Douglas Luiz', position: 'Meio-campista', club: 'Juventus' },
  // Atacantes
  { name: 'Vinícius Júnior', position: 'Atacante', club: 'Real Madrid' },
  { name: 'Rodrygo', position: 'Atacante', club: 'Real Madrid' },
  { name: 'Raphinha', position: 'Atacante', club: 'Barcelona' },
  { name: 'Endrick', position: 'Atacante', club: 'Real Madrid' },
  { name: 'Richarlison', position: 'Atacante', club: 'Tottenham' },
  { name: 'João Pedro', position: 'Atacante', club: 'Brighton' },
  { name: 'Igor Thiago', position: 'Atacante', club: 'Brentford' },
  { name: 'Luiz Henrique', position: 'Atacante', club: 'Botafogo/Zenit' },
  { name: 'Matheus Cunha', position: 'Atacante', club: 'Wolverhampton' },
  { name: 'Gabriel Martinelli', position: 'Atacante', club: 'Arsenal' },
  { name: 'Rayan', position: 'Atacante', club: 'Vasco' },
  { name: 'Estêvão', position: 'Atacante', club: 'Palmeiras/Chelsea' },
  { name: 'Vitor Roque', position: 'Atacante', club: 'Palmeiras' },
  { name: 'Igor Jesus', position: 'Atacante', club: 'Botafogo' },
  { name: 'Savinho', position: 'Atacante', club: 'Manchester City' },
  { name: 'Neymar', position: 'Atacante', club: 'Santos' },
];

export const SIGLAS: Record<string, string> = {
  'Brasil': 'BRA',
  'Alemanha': 'ALE',
  'Estados Unidos': 'EUA',
  'África do Sul': 'AFS',
  'Arábia Saudita': 'KSA',
  'Costa Rica': 'CRC',
  'Nova Zelândia': 'NZE',
  'Cabo Verde': 'CBV',
  'Costa do Marfim': 'CIV',
  'RD Congo': 'RDC',
  'Coreia do Sul': 'KOR',
  'Reino Unido': 'UK',
  'Inglaterra': 'ING',
  'Holanda': 'HOL',
  'França': 'FRA',
  'Espanha': 'ESP',
  'Portugal': 'POR',
  'Argentina': 'ARG',
  'Uruguai': 'URU',
  'México': 'MEX',
  'Japão': 'JAP',
  'Suíça': 'SUI',
  'Croácia': 'CRO',
  'Bélgica': 'BEL',
  'Senegal': 'SEN',
  'Marrocos': 'MAR',
  'Colômbia': 'COL',
  'Curaçao': 'CUR',
  'Haiti': 'HAI',
  'Argélia': 'ALG',
  'Austrália': 'AUS',
  'Dinamarca': 'DIN',
  'Itália': 'ITA',
  'Equador': 'EQU',
  'Canadá': 'CAN',
  'Bósnia': 'BOS',
  'Paraguai': 'PAR',
  'Turquia': 'TUR',
  'Egito': 'EGI',
  'Irã': 'IRA',
  'Iraque': 'IRQ',
  'Noruega': 'NOR',
  'Áustria': 'AUT',
  'Jordânia': 'JOR',
  'Gana': 'GHA',
  'Panamá': 'PAN',
  'Uzbequistão': 'UZB'
};

export const FIXED_THIRD_ASSIGNMENTS: Record<string, string> = {
  m74: "A",
  m77: "C",
  m79: "F",
  m80: "E",
  m81: "B",
  m82: "H",
  m85: "G",
  m87: "D",
};

export const WORLD_CUP_MATCHES: Match[] = [
  // FASE DE GRUPOS
  { id: 'm1', teamA: 'México', teamB: 'África do Sul', group: 'A', date: '2026-06-11T16:00:00Z', location: 'Cidade do México (México)', status: 'pending' },
  { id: 'm2', teamA: 'Coreia do Sul', teamB: 'República Tcheca', group: 'A', date: '2026-06-11T23:00:00Z', location: 'Guadalajara (México)', status: 'pending' },
  { id: 'm3', teamA: 'Canadá', teamB: 'Bósnia', group: 'B', date: '2026-06-12T16:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm4', teamA: 'Estados Unidos', teamB: 'Paraguai', group: 'D', date: '2026-06-12T22:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm5', teamA: 'Austrália', teamB: 'Turquia', group: 'D', date: '2026-06-13T01:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm6', teamA: 'Qatar', teamB: 'Suíça', group: 'B', date: '2026-06-13T16:00:00Z', location: 'San Francisco (Estados Unidos)', status: 'pending' },
  { id: 'm7', teamA: 'Brasil', teamB: 'Marrocos', group: 'C', date: '2026-06-13T19:00:00Z', location: 'Nova York (Estados Unidos)', status: 'pending' },
  { id: 'm8', teamA: 'Haiti', teamB: 'Escócia', group: 'C', date: '2026-06-13T22:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm9', teamA: 'Alemanha', teamB: 'Curaçao', group: 'E', date: '2026-06-14T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm10', teamA: 'Holanda', teamB: 'Japão', group: 'F', date: '2026-06-14T17:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm11', teamA: 'Costa do Marfim', teamB: 'Equador', group: 'E', date: '2026-06-14T20:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm12', teamA: 'Suécia', teamB: 'Tunísia', group: 'F', date: '2026-06-14T23:00:00Z', location: 'Monterrey (México)', status: 'pending' },
  { id: 'm13', teamA: 'Espanha', teamB: 'Cabo Verde', group: 'H', date: '2026-06-15T13:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm14', teamA: 'Bélgica', teamB: 'Egito', group: 'G', date: '2026-06-15T16:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm15', teamA: 'Arábia Saudita', teamB: 'Uruguai', group: 'H', date: '2026-06-15T19:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm16', teamA: 'Irã', teamB: 'Nova Zelândia', group: 'G', date: '2026-06-15T22:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm17', teamA: 'França', teamB: 'Senegal', group: 'I', date: '2026-06-16T16:00:00Z', location: 'Nova York (Estados Unidos)', status: 'pending' },
  { id: 'm18', teamA: 'Iraque', teamB: 'Noruega', group: 'I', date: '2026-06-16T19:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm19', teamA: 'Argentina', teamB: 'Argélia', group: 'J', date: '2026-06-16T22:00:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },
  { id: 'm20', teamA: 'Áustria', teamB: 'Jordânia', group: 'J', date: '2026-06-17T01:00:00Z', location: 'San Francisco (Estados Unidos)', status: 'pending' },
  { id: 'm21', teamA: 'Portugal', teamB: 'RD Congo', group: 'K', date: '2026-06-17T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm22', teamA: 'Inglaterra', teamB: 'Croácia', group: 'L', date: '2026-06-17T17:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm23', teamA: 'Gana', teamB: 'Panamá', group: 'L', date: '2026-06-17T20:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm24', teamA: 'Uzbequistão', teamB: 'Colômbia', group: 'K', date: '2026-06-17T23:00:00Z', location: 'Cidade do México (México)', status: 'pending' },
  { id: 'm25', teamA: 'República Tcheca', teamB: 'África do Sul', group: 'A', date: '2026-06-18T13:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm26', teamA: 'Suíça', teamB: 'Bósnia', group: 'B', date: '2026-06-18T16:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm27', teamA: 'Canadá', teamB: 'Qatar', group: 'B', date: '2026-06-18T19:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm28', teamA: 'México', teamB: 'Coreia do Sul', group: 'A', date: '2026-06-18T22:00:00Z', location: 'Guadalajara (México)', status: 'pending' },
  { id: 'm29', teamA: 'Turquia', teamB: 'Paraguai', group: 'D', date: '2026-06-19T01:00:00Z', location: 'San Francisco (Estados Unidos)', status: 'pending' },
  { id: 'm30', teamA: 'Estados Unidos', teamB: 'Austrália', group: 'D', date: '2026-06-19T16:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm31', teamA: 'Escócia', teamB: 'Marrocos', group: 'C', date: '2026-06-19T19:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm32', teamA: 'Brasil', teamB: 'Haiti', group: 'C', date: '2026-06-19T22:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm33', teamA: 'Holanda', teamB: 'Suécia', group: 'F', date: '2026-06-20T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm34', teamA: 'Alemanha', teamB: 'Costa do Marfim', group: 'E', date: '2026-06-20T17:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm35', teamA: 'Equador', teamB: 'Curaçao', group: 'E', date: '2026-06-20T21:00:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },
  { id: 'm36', teamA: 'Tunísia', teamB: 'Japão', group: 'F', date: '2026-06-21T01:00:00Z', location: 'Monterrey (México)', status: 'pending' },
  { id: 'm37', teamA: 'Espanha', teamB: 'Arábia Saudita', group: 'H', date: '2026-06-21T13:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm38', teamA: 'Bélgica', teamB: 'Irã', group: 'G', date: '2026-06-21T16:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm39', teamA: 'Uruguai', teamB: 'Cabo Verde', group: 'H', date: '2026-06-21T19:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm40', teamA: 'Nova Zelândia', teamB: 'Egito', group: 'G', date: '2026-06-21T22:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm41', teamA: 'Argentina', teamB: 'Áustria', group: 'J', date: '2026-06-22T14:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm42', teamA: 'França', teamB: 'Iraque', group: 'I', date: '2026-06-22T18:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm43', teamA: 'Noruega', teamB: 'Senegal', group: 'I', date: '2026-06-22T21:00:00Z', location: 'Nova York (Estados Unidos)', status: 'pending' },
  { id: 'm44', teamA: 'Jordânia', teamB: 'Argélia', group: 'J', date: '2026-06-23T00:00:00Z', location: 'San Francisco (Estados Unidos)', status: 'pending' },
  { id: 'm45', teamA: 'Portugal', teamB: 'Uzbequistão', group: 'K', date: '2026-06-23T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm46', teamA: 'Inglaterra', teamB: 'Gana', group: 'L', date: '2026-06-23T17:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm47', teamA: 'Panamá', teamB: 'Croácia', group: 'L', date: '2026-06-23T20:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm48', teamA: 'Colômbia', teamB: 'RD Congo', group: 'K', date: '2026-06-23T23:00:00Z', location: 'Guadalajara (México)', status: 'pending' },
  { id: 'm49', teamA: 'Suíça', teamB: 'Canadá', group: 'B', date: '2026-06-24T16:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm50', teamA: 'Bósnia', teamB: 'Qatar', group: 'B', date: '2026-06-24T16:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm51', teamA: 'Escócia', teamB: 'Brasil', group: 'C', date: '2026-06-24T19:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm52', teamA: 'Marrocos', teamB: 'Haiti', group: 'C', date: '2026-06-24T19:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm53', teamA: 'República Tcheca', teamB: 'México', group: 'A', date: '2026-06-24T22:00:00Z', location: 'Cidade do México (México)', status: 'pending' },
  { id: 'm54', teamA: 'África do Sul', teamB: 'Coreia do Sul', group: 'A', date: '2026-06-24T22:00:00Z', location: 'Monterrey (México)', status: 'pending' },
  { id: 'm55', teamA: 'Equador', teamB: 'Alemanha', group: 'E', date: '2026-06-25T17:00:00Z', location: 'Nova York (Estados Unidos)', status: 'pending' },
  { id: 'm56', teamA: 'Curaçao', teamB: 'Costa do Marfim', group: 'E', date: '2026-06-25T17:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm57', teamA: 'Tunísia', teamB: 'Holanda', group: 'F', date: '2026-06-25T20:00:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },
  { id: 'm58', teamA: 'Japão', teamB: 'Suécia', group: 'F', date: '2026-06-25T20:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm59', teamA: 'Turquia', teamB: 'Estados Unidos', group: 'D', date: '2026-06-25T23:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm60', teamA: 'Paraguai', teamB: 'Austrália', group: 'D', date: '2026-06-25T23:00:00Z', location: 'San Francisco (Estados Unidos)', status: 'pending' },
  { id: 'm61', teamA: 'Noruega', teamB: 'França', group: 'I', date: '2026-06-26T16:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm62', teamA: 'Senegal', teamB: 'Iraque', group: 'I', date: '2026-06-26T16:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm63', teamA: 'Uruguai', teamB: 'Espanha', group: 'H', date: '2026-06-26T21:00:00Z', location: 'Guadalajara (México)', status: 'pending' },
  { id: 'm64', teamA: 'Cabo Verde', teamB: 'Arábia Saudita', group: 'H', date: '2026-06-26T21:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm65', teamA: 'Egito', teamB: 'Irã', group: 'G', date: '2026-06-27T00:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm66', teamA: 'Nova Zelândia', teamB: 'Bélgica', group: 'G', date: '2026-06-27T00:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm67', teamA: 'Panamá', teamB: 'Inglaterra', group: 'L', date: '2026-06-27T18:00:00Z', location: 'Nova York (Estados Unidos)', status: 'pending' },
  { id: 'm68', teamA: 'Croácia', teamB: 'Gana', group: 'L', date: '2026-06-27T18:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm69', teamA: 'Colômbia', teamB: 'Portugal', group: 'K', date: '2026-06-27T20:30:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm70', teamA: 'RD Congo', teamB: 'Uzbequistão', group: 'K', date: '2026-06-27T20:30:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm71', teamA: 'Jordânia', teamB: 'Argentina', group: 'J', date: '2026-06-27T23:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm72', teamA: 'Argélia', teamB: 'Áustria', group: 'J', date: '2026-06-27T23:00:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },

  // 32-AVOS DE FINAL (ROUND OF 32)
  { id: 'm73', teamA: '2º Grupo A', teamB: '2º Grupo B', group: 'R32', date: '2026-06-28T16:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm74', teamA: '1º Grupo E', teamB: '3º A/B/C/D/F', group: 'R32', date: '2026-06-29T17:30:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm75', teamA: '1º Grupo F', teamB: '2º Grupo C', group: 'R32', date: '2026-06-29T22:00:00Z', location: 'Monterrey (México)', status: 'pending' },
  { id: 'm76', teamA: '1º Grupo C', teamB: '2º Grupo F', group: 'R32', date: '2026-06-29T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm77', teamA: '1º Grupo I', teamB: '3º C/D/F/G/H', group: 'R32', date: '2026-06-30T18:00:00Z', location: 'Nova York/Nova Jersey (Estados Unidos)', status: 'pending' },
  { id: 'm78', teamA: '2º Grupo E', teamB: '2º Grupo I', group: 'R32', date: '2026-06-30T14:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm79', teamA: '1º Grupo A', teamB: '3º C/E/F/H/I', group: 'R32', date: '2026-06-30T22:00:00Z', location: 'Cidade do México (México)', status: 'pending' },
  { id: 'm80', teamA: '1º Grupo L', teamB: '3º E/H/I/J/K', group: 'R32', date: '2026-07-01T13:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm81', teamA: '1º Grupo D', teamB: '3º B/E/F/I/J', group: 'R32', date: '2026-07-01T21:00:00Z', location: 'Santa Clara (Estados Unidos)', status: 'pending' },
  { id: 'm82', teamA: '1º Grupo G', teamB: '3º A/E/H/I/J', group: 'R32', date: '2026-07-01T17:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm83', teamA: '2º Grupo K', teamB: '2º Grupo L', group: 'R32', date: '2026-07-02T20:00:00Z', location: 'Toronto (Canadá)', status: 'pending' },
  { id: 'm84', teamA: '1º Grupo H', teamB: '2º Grupo J', group: 'R32', date: '2026-07-02T16:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm85', teamA: '1º Grupo B', teamB: '3º E/F/G/I/J', group: 'R32', date: '2026-07-02T00:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },
  { id: 'm86', teamA: '1º Grupo J', teamB: '2º Grupo H', group: 'R32', date: '2026-07-03T19:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm87', teamA: '1º Grupo K', teamB: '3º D/E/I/J/L', group: 'R32', date: '2026-07-03T22:30:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },
  { id: 'm88', teamA: '2º Grupo D', teamB: '2º Grupo G', group: 'R32', date: '2026-07-03T15:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },

  // OITAVAS DE FINAL (ROUND OF 16)
  { id: 'm89', teamA: 'Venc. Jogo 74', teamB: 'Venc. Jogo 77', group: 'R16', date: '2026-07-04T18:00:00Z', location: 'Filadélfia (Estados Unidos)', status: 'pending' },
  { id: 'm90', teamA: 'Venc. Jogo 73', teamB: 'Venc. Jogo 75', group: 'R16', date: '2026-07-04T14:00:00Z', location: 'Houston (Estados Unidos)', status: 'pending' },
  { id: 'm91', teamA: 'Venc. Jogo 76', teamB: 'Venc. Jogo 78', group: 'R16', date: '2026-07-05T17:00:00Z', location: 'Nova York/Nova Jersey (Estados Unidos)', status: 'pending' },
  { id: 'm92', teamA: 'Venc. Jogo 79', teamB: 'Venc. Jogo 80', group: 'R16', date: '2026-07-05T21:00:00Z', location: 'Cidade do México (México)', status: 'pending' },
  { id: 'm93', teamA: 'Venc. Jogo 83', teamB: 'Venc. Jogo 84', group: 'R16', date: '2026-07-06T16:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm94', teamA: 'Venc. Jogo 81', teamB: 'Venc. Jogo 82', group: 'R16', date: '2026-07-06T21:00:00Z', location: 'Seattle (Estados Unidos)', status: 'pending' },
  { id: 'm95', teamA: 'Venc. Jogo 86', teamB: 'Venc. Jogo 88', group: 'R16', date: '2026-07-07T13:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },
  { id: 'm96', teamA: 'Venc. Jogo 85', teamB: 'Venc. Jogo 87', group: 'R16', date: '2026-07-07T17:00:00Z', location: 'Vancouver (Canadá)', status: 'pending' },

  // QUARTAS DE FINAL
  { id: 'm97', teamA: 'Venc. Jogo 89', teamB: 'Venc. Jogo 90', group: 'QF', date: '2026-07-09T17:00:00Z', location: 'Boston (Estados Unidos)', status: 'pending' },
  { id: 'm98', teamA: 'Venc. Jogo 93', teamB: 'Venc. Jogo 94', group: 'QF', date: '2026-07-10T16:00:00Z', location: 'Los Angeles (Estados Unidos)', status: 'pending' },
  { id: 'm99', teamA: 'Venc. Jogo 91', teamB: 'Venc. Jogo 92', group: 'QF', date: '2026-07-11T18:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },
  { id: 'm100', teamA: 'Venc. Jogo 95', teamB: 'Venc. Jogo 96', group: 'QF', date: '2026-07-11T22:00:00Z', location: 'Kansas City (Estados Unidos)', status: 'pending' },

  // SEMIFINAIS
  { id: 'm101', teamA: 'Venc. Jogo 97', teamB: 'Venc. Jogo 98', group: 'SF', date: '2026-07-14T16:00:00Z', location: 'Dallas (Estados Unidos)', status: 'pending' },
  { id: 'm102', teamA: 'Venc. Jogo 99', teamB: 'Venc. Jogo 100', group: 'SF', date: '2026-07-15T16:00:00Z', location: 'Atlanta (Estados Unidos)', status: 'pending' },

  // DISPUTA DE 3º LUGAR
  { id: 'm103', teamA: 'Perd. Jogo 101', teamB: 'Perd. Jogo 102', group: '3RD', date: '2026-07-18T18:00:00Z', location: 'Miami (Estados Unidos)', status: 'pending' },

  // FINAL
  { id: 'm104', teamA: 'Venc. Jogo 101', teamB: 'Venc. Jogo 102', group: 'FINAL', date: '2026-07-19T16:00:00Z', location: 'Nova York/Nova Jersey (Estados Unidos)', status: 'pending' },
];
